---
- name: Package Management with APT (Local)
  hosts: local
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install git
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Install multiple packages
      apt:
        name:
          - wget
          - curl
          - vim
          - htop
        state: present
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Remove nano
      apt:
        name: nano
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"
