---
- name: Infrastructure Setup (Local)
  hosts: local
  become: yes

  vars:
    common_packages:
      - git
      - wget
      - curl
      - vim

  tasks:
    - name: Install common packages
      package:
        name: "{{ common_packages }}"
        state: present

    - name: Install web server
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Start web service
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: |
          <h1>Hi world, from Ansible</h1>
          <p>Managed by Ansible</p>
          <p>OS: {{ ansible_distribution }}</p>
        dest: /var/www/html/index.html
