---
- name: Universal Package Management (Local)
  hosts: local
  become: yes
  tasks:
    - name: Install git (RedHat)
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install git (Debian)
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install dev tools (RedHat)
      yum:
        name:
          - gcc
          - make
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install dev tools (Debian)
      apt:
        name:
          - build-essential
        state: present
      when: ansible_os_family == "Debian"
