---
- name: Package Management with YUM (Local)
  hosts: local
  become: yes
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install multiple packages
      yum:
        name:
          - wget
          - curl
          - vim
        state: present
      when: ansible_os_family == "RedHat"

    - name: Update all packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Remove telnet
      yum:
        name: telnet
        state: absent
      when: ansible_os_family == "RedHat"
