---
- name: Manage Firewall Zones
  hosts: localhost
  become: yes

  tasks:
    - name: List all available zones
      command: firewall-cmd --get-zones
      register: available_zones

    - name: Display available zones
      debug:
        msg: "Available zones: {{ available_zones.stdout }}"

    - name: Get default zone
      command: firewall-cmd --get-default-zone
      register: default_zone

    - name: Display default zone
      debug:
        msg: "Default zone: {{ default_zone.stdout }}"

    - name: Create custom zone DMZ
      copy:
        dest: /etc/firewalld/zones/dmz-custom.xml
        content: |
          <?xml version="1.0" encoding="utf-8"?>
          <zone>
            <short>DMZ Custom</short>
            <description>Custom DMZ zone</description>
          </zone>
        mode: '0644'

    - name: Reload firewalld to recognize new zone
      command: firewall-cmd --reload

    - name: Configure DMZ zone with specific services
      ansible.posix.firewalld:
        zone: dmz-custom
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https
        - ssh

    - name: List zones and their configurations
      command: firewall-cmd --list-all-zones
      register: all_zones

    - name: Display zones configuration
      debug:
        msg: "{{ all_zones.stdout_lines[:50] }}"

