---
- name: Basic Loops Demo
  hosts: local
  gather_facts: yes
  become: true

  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip
        - tree
        - nano

    - name: Create users
      user:
        name: "{{ item }}"
        shell: /bin/bash
        create_home: yes
      loop:
        - alice
        - bob
        - charlie

    - name: Create directories
      file:
        path: "/opt/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - app1
        - app2
        - logs
        - backups
