---
- name: Advanced Services
  hosts: webservers
  become: yes

  vars:
    redhat_packages:
      - httpd
      - cronie

    debian_packages:
      - apache2
      - cron

  tasks:
    - name: Detect OS family
      set_fact:
        service_packages: "{{ redhat_packages if ansible_os_family == 'RedHat' else debian_packages }}"

    - name: Install required packages
      package:
        name: "{{ service_packages }}"
        state: present
      notify: Restart services

    - name: Ensure services are started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ service_packages }}"

    - name: Collect service status
      systemd:
        name: "{{ item }}"
      loop: "{{ service_packages }}"
      register: service_status

    - name: Validate services are running
      assert:
        that:
          - item.status.ActiveState == "active"
        fail_msg: "Service {{ item.item }} is NOT running"
        success_msg: "Service {{ item.item }} is running correctly"
      loop: "{{ service_status.results }}"

  handlers:
    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ service_packages }}"
