---
- name: Health Check
  hosts: webservers
  become: yes
  vars:
    web_service: httpd

  tasks:
    - name: Test config
      command: httpd -t

    - name: Memory usage
      shell: ps aux | grep httpd | grep -v grep

    - name: Uptime
      shell: systemctl show httpd --property=ActiveEnterTimestamp
