---
- name: Service Management
  hosts: webservers
  become: yes
  vars:
    web_service_name: httpd

  tasks:
    - name: Create index page
      copy:
        content: |
          <h1>Ansible Managed Server</h1>
          <p>Host: {{ inventory_hostname }}</p>
        dest: /var/www/html/index.html
      notify: restart web service

    - name: Start and enable service
      systemd:
        name: "{{ web_service_name }}"
        state: started
        enabled: yes

    - name: Wait for service
      wait_for:
        port: 80
        timeout: 20
      delegate_to: localhost

  handlers:
    - name: restart web service
      systemd:
        name: "{{ web_service_name }}"
        state: restarted
