---
- name: Configure User Password Policies and Expiration
  hosts: webservers
  become: yes
  vars:
    password_policies:
      - username: alice
        max_days: 90
        min_days: 7
        warn_days: 14
        expire_date: "2024-12-31"
      - username: bob
        max_days: 60
        min_days: 5
        warn_days: 10
        expire_date: "2024-11-30"
      - username: charlie
        max_days: 180
        min_days: 14
        warn_days: 21
        expire_date: "2025-06-30"

  tasks:
    - name: Set password aging policies
      shell: |
        chage -M {{ item.max_days }} {{ item.username }}
        chage -m {{ item.min_days }} {{ item.username }}
        chage -W {{ item.warn_days }} {{ item.username }}
      loop: "{{ password_policies }}"
      tags: password_aging

    - name: Set account expiration dates
      user:
        name: "{{ item.username }}"
        expires: "{{ (item.expire_date + ' 00:00:00') | to_datetime('%Y-%m-%d %H:%M:%S') | int }}"
      loop: "{{ password_policies }}"
      tags: account_expiry

    - name: Display password policy information
      shell: chage -l {{ item.username }}
      register: password_info
      loop: "{{ password_policies }}"
      tags: info

    - name: Show password policy details
      debug:
        msg: "{{ password_info.results }}"
      tags: info
