---
- name: Automate User and Group Management
  hosts: webservers
  become: yes

  vars:
    user_groups:
      - name: developers
        gid: 3001
      - name: testers
        gid: 3002
      - name: admins
        gid: 3003

    system_users:
      - username: alice
        full_name: "Alice Johnson"
        primary_group: developers
        secondary_groups:
          - admins
        shell: /bin/bash
        create_home: yes
        password: "{{ 'Password123!' | password_hash('sha512') }}"

      - username: bob
        full_name: "Bob Smith"
        primary_group: testers
        secondary_groups:
          - developers
        shell: /bin/bash
        create_home: yes
        password: "{{ 'Password123!' | password_hash('sha512') }}"

      - username: charlie
        full_name: "Charlie Brown"
        primary_group: admins
        secondary_groups: []
        shell: /bin/bash
        create_home: yes
        password: "{{ 'Password123!' | password_hash('sha512') }}"

  tasks:
    - name: Create system groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ user_groups }}"
      tags: groups

    - name: Create system users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.full_name }}"
        group: "{{ item.primary_group }}"
        groups: "{{ item.secondary_groups | join(',') if item.secondary_groups else omit }}"
        shell: "{{ item.shell }}"
        create_home: "{{ item.create_home }}"
        password: "{{ item.password }}"
        update_password: on_create
        state: present
      loop: "{{ system_users }}"
      tags: users

    - name: Verify users exist
      command: id "{{ item.username }}"
      loop: "{{ system_users }}"
      register: user_check
      changed_when: false

    - name: Show verification result
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ user_check.results }}"
      tags: verify

