---
- name: Facts Exploration (Local)
  hosts: local
  gather_facts: yes

  tasks:
    - debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          Memory: {{ ansible_memtotal_mb }} MB
          CPU Cores: {{ ansible_processor_cores }}

    - debug:
        msg: |
          IP: {{ ansible_default_ipv4.address }}
          Interface: {{ ansible_default_ipv4.interface }}
