---
- name: Variables and Facts Demonstration (Local)
  hosts: local
  gather_facts: yes

  vars:
    application_name: "WebServer"
    port_number: 8080
    enable_ssl: true

    required_packages:
      - git
      - curl
      - vim

    database_config:
      host: "localhost"
      port: 3306
      name: "webapp_db"
      user: "webapp_user"

  tasks:
    - debug:
        msg: "Setting up {{ application_name }} on port {{ port_number }}"

    - debug:
        msg: "SSL is {{ 'enabled' if enable_ssl else 'disabled' }}"

    - debug:
        msg: "Package: {{ item }}"
      loop: "{{ required_packages }}"

    - debug:
        msg: "Database {{ database_config.name }} on {{ database_config.host }}:{{ database_config.port }}"
