---
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_connection: local
          datacenter: east
        web02:
          ansible_connection: local
          datacenter: west
      vars:
        http_port: 80

    databases:
      hosts:
        db01:
          ansible_connection: local
          db_role: master
        db02:
          ansible_connection: local
          db_role: slave
  vars:
    environment: production
    backup_enabled: true
